import * as T from "$book";

export const chapter = T.BookChapter.from_exposition([
    T.List.numbered([
        T.Prose.parse(`
            Consider the rotational symmetries of a regular hexagon. These are rotations by $$0^\\circ, 60^\\circ, 120^\\circ, 180^\\circ, 240^\\circ,$$ and $$300^\\circ$$.
        `),
        T.Prose.parse(`
            Let $$r$$ be the rotation by $$60^\\circ$$. Then all rotations can be expressed as powers of $$r$$:
            - $$r^0 = 0^\\circ$$ rotation (identity)
            - $$r^1 = 60^\\circ$$ rotation
            - $$r^2 = 120^\\circ$$ rotation
            - $$r^3 = 180^\\circ$$ rotation
            - $$r^4 = 240^\\circ$$ rotation
            - $$r^5 = 300^\\circ$$ rotation
            - $$r^6 = 360^\\circ$$ rotation = identity
        `),
        T.Prose.parse(`
            The group operation table is:
            $$
            \\begin{array}{c|cccccc}
            \\circ & r^0 & r^1 & r^2 & r^3 & r^4 & r^5 \\\\
            \\hline
            r^0 & r^0 & r^1 & r^2 & r^3 & r^4 & r^5 \\\\
            r^1 & r^1 & r^2 & r^3 & r^4 & r^5 & r^0 \\\\
            r^2 & r^2 & r^3 & r^4 & r^5 & r^0 & r^1 \\\\
            r^3 & r^3 & r^4 & r^5 & r^0 & r^1 & r^2 \\\\
            r^4 & r^4 & r^5 & r^0 & r^1 & r^2 & r^3 \\\\
            r^5 & r^5 & r^0 & r^1 & r^2 & r^3 & r^4
            \\end{array}
            $$
        `),
        T.Prose.parse(`
            This group is cyclic because:
            1. It is generated by a single element $$r$$
            2. Every element can be written as a power of $$r$$
            3. The group is isomorphic to $$\\mathbb{Z}_6$$ under addition
        `),
        T.Prose.parse(`
            Note that $$r^3$$ (180° rotation) is an element of order 2, and $$r^2$$ and $$r^4$$ are elements of order 3.
        `),
    ]),
], 
    T.Prose.parse(`Example: Rotational Symmetries of a Regular Hexagon`)
); 