import * as T from "$lib/book";

export const chapter = T.BookChapter.from_exposition([
    T.List.numbered([
        T.Prose.parse(`
            Consider the full symmetry group of a square, which includes both rotations and reflections.
        `),
        T.Prose.parse(`
            Let $$r$$ be a $$90^\\circ$$ rotation and $$s$$ be a reflection across the vertical axis. The group has 8 elements:
            - Rotations: $$\\{1, r, r^2, r^3\\}$$ (where $$1$$ is the identity)
            - Reflections: $$\\{s, sr, sr^2, sr^3\\}$$
        `),
        T.Prose.parse(`
            The group operation table (partial) shows non-commutativity:
            $$
            \\begin{array}{c|cc}
            \\circ & r & s \\\\
            \\hline
            r & r^2 & sr \\\\
            s & sr^3 & 1
            \\end{array}
            $$
            Note that $$sr \\neq rs$$, showing the group is non-abelian.
        `),
        T.Prose.parse(`
            This group is not cyclic because:
            1. No single element generates all 8 elements
            2. The maximum order of any element is 4:
               - Rotations have orders: 1 (identity), 2 (180°), 4 (90° and 270°)
               - Reflections have order 2
            3. The group is non-abelian, while all cyclic groups are abelian
        `),
        T.Prose.parse(`
            This is the dihedral group $$D_4$$, which requires at least two generators ($$r$$ and $$s$$) and cannot be generated by a single element.
        `),
    ]),
], 
    T.Prose.parse(`Non-Example: Full Symmetry Group of a Square (Including Reflections)`)
); 