import * as T from "$lib/tex";

export const z = [

    T.Inline.parse(`
        Recall the ideals of the unital commutative ring $$\\mathbb{Z}$$. For all $$n$$ in $$\\mathbb{Z}$$, there exists a principle ideal $$\\langle n \\rangle$$ generated by $$n$$.
    `),

    T.Block.from_single_statement(
        new T.Tex(`\\langle n \\rangle = \\{ nk \\mid k \\in \\mathbb{Z} \\}`)
    ),

    T.Inline.parse(`
        Recall the following specific ideals of $$\\mathbb{Z}$$.
    `),

    new T.List([
        T.Inline.parse(`
            $$\\langle 0 \\rangle = 
            \\{ 0 \\}$$
        `),
        T.Inline.parse(`
            $$\\langle 1 \\rangle = 
            \\langle -1 \\rangle = 
            \\{ 0, \\pm 1, \\pm 2, \\pm 3, \\ldots \\}$$
        `),
        T.Inline.parse(`
            $$\\langle 2 \\rangle = 
            \\langle -2 \\rangle = 
            \\{ 0, \\pm 2, \\pm 4, \\pm 6, \\ldots \\}$$
        `),
        T.Inline.parse(`
            $$\\langle 3 \\rangle = \\langle -3 \\rangle = 
            \\{ 0, \\pm 3, \\pm 6, \\pm 9, \\ldots \\}$$
        `),
        T.Inline.parse(`
            $$\\langle 4 \\rangle = \\langle -4 \\rangle = 
            \\{ 0, \\pm 4, \\pm 8, \\pm 12, \\ldots \\}$$
        `),
        T.Inline.parse(`
            $$\\langle 5 \\rangle = \\langle -5 \\rangle = 
            \\{ 0, \\pm 5, \\pm 10, \\pm 15, \\ldots \\}$$
        `),
        T.Inline.parse(`
            $$\\langle 6 \\rangle = \\langle -6 \\rangle = 
            \\{ 0, \\pm 6, \\pm 12, \\pm 18, \\ldots \\}$$
        `),
    ]),

    new T.List([
        T.Inline.parse(`
            $$\\langle 0 \\rangle$$ is contained in all other ideals, and thus, is not maximal.
        `),
        T.Inline.parse(`
            $$\\langle 1 \\rangle$$ is the unital ideal, and thus, not a proper ideal, and thus, not maximal.
        `),
        T.Inline.parse(`
            $$\\langle 2 \\rangle$$ is maximal, as it is not contained in any other ideal.
        `),
        T.Inline.parse(`
            $$\\langle 3 \\rangle$$ is maximal, as it is not contained in any other ideal.
        `),
        T.Inline.parse(`
            $$\\langle 4 \\rangle$$ is contained in $$\\langle 2 \\rangle$$, and thus, is not maximal.
        `),
        T.Inline.parse(`
            $$\\langle 5 \\rangle$$ is maximal, as it is not contained in any other ideal.
        `),
        T.Inline.parse(`
            $$\\langle 6 \\rangle$$ is contained in both $$\\langle 2 \\rangle$$ and $$\\langle 3 \\rangle$$, and thus, is not maximal.
        `),
    ]),

    T.Inline.parse(`
        Evidently, there is an obvious pattern here. All ideals of the form $$\\langle n \\rangle$$ are maximal, when $$n$$ is a prime number, and not maximal otherwise.
    `),

];