import * as T from "$lib/book";
import { Webpage } from "$lib/content/utils";

export const chapter = T.BookChapter.book_from_exposition([
    T.Prose.parse(`
        A principal ideal domain is a ring that satisfies the principal ideal condition on (one-sided) ideals; 
        every ideal is generated by a single element.
    `),
], T.Prose.parse(`Principal Ideal Domains`));

export const page = Webpage.from_chapter(chapter);
/*

principal ideal domains
- structure theorem for finitely generated modules over a principal ideal domain (PID)
- In a principal ideal domain, any two elements a,b have a greatest common divisor, which may be obtained as a generator of the ideal (a, b).
- Every principal ideal domain is a unique factorization domain (UFD)
- a Dedekind–Hasse norm is a function on an integral domain that generalises the notion of a Euclidean function on Euclidean domains. To wit, they proved that if an integral domain R has a Dedekind–Hasse norm, then R is a principal ideal domain.
*/