import * as T from "$book";

export const chapter = T.Exposition.from([
    T.List.numbered([
        T.Prose.parse(`
            Consider the 4th roots of unity under multiplication. These are the complex numbers $$\\{1, i, -1, -i\\}$$ where $$i = \\sqrt{-1}$$.
        `),
        T.Prose.parse(`
            Let $$\\omega = e^{2\\pi i/4} = i$$. Then all roots can be expressed as powers of $$\\omega$$:
            - $$\\omega^0 = 1$$
            - $$\\omega^1 = i$$
            - $$\\omega^2 = -1$$
            - $$\\omega^3 = -i$$
            - $$\\omega^4 = 1$$
        `),
        T.Prose.parse(`
            The group operation table is:
            $$
            \\begin{array}{c|cccc}
            \\cdot & 1 & i & -1 & -i \\\\
            \\hline
            1 & 1 & i & -1 & -i \\\\
            i & i & -1 & -i & 1 \\\\
            -1 & -1 & -i & 1 & i \\\\
            -i & -i & 1 & i & -1
            \\end{array}
            $$
        `),
        T.Prose.parse(`
            This group is cyclic because:
            1. It is generated by a single element $$\\omega = i$$
            2. Every element can be written as a power of $$\\omega$$
            3. The group is isomorphic to $$\\mathbb{Z}_4$$ under addition
        `),
    ]),
], 
    T.Prose.parse(`Example: 4th Roots $$\\zeta_4$$`)
); 