import * as T from "$book";

export const chapter = T.Exposition.from([
    T.List.numbered([
        T.Prose.parse(`
            Consider the 6th roots of unity under multiplication. These are the complex numbers $$\\{1, \\omega, \\omega^2, \\omega^3, \\omega^4, \\omega^5\\}$$ where $$\\omega = e^{2\\pi i/6}$$.
        `),
        T.Prose.parse(`
            In terms of real and imaginary parts:
            - $$\\omega^0 = 1$$
            - $$\\omega^1 = \\frac{1}{2} + \\frac{\\sqrt{3}}{2}i$$
            - $$\\omega^2 = -\\frac{1}{2} + \\frac{\\sqrt{3}}{2}i$$
            - $$\\omega^3 = -1$$
            - $$\\omega^4 = -\\frac{1}{2} - \\frac{\\sqrt{3}}{2}i$$
            - $$\\omega^5 = \\frac{1}{2} - \\frac{\\sqrt{3}}{2}i$$
        `),
        T.Prose.parse(`
            The group operation table (partial) shows the cyclic nature:
            $$
            \\begin{array}{c|cc}
            \\cdot & \\omega & \\omega^2 \\\\
            \\hline
            \\omega & \\omega^2 & \\omega^3 \\\\
            \\omega^2 & \\omega^3 & \\omega^4
            \\end{array}
            $$
        `),
        T.Prose.parse(`
            This group is cyclic because:
            1. It is generated by a single element $$\\omega$$
            2. Every element can be written as a power of $$\\omega$$
            3. The group is isomorphic to $$\\mathbb{Z}_6$$ under addition
        `),
        T.Prose.parse(`
            Note that $$\\omega^3$$ is an element of order 2, and $$\\omega^2$$ and $$\\omega^4$$ are elements of order 3.
        `),
    ]),
], 
    T.Prose.parse(`Example: 6th Roots $$\\zeta_6$$`)
); 