import * as T from "$book";

export const nilradical = T.Exposition.from([
    T.List.numbered([
        T.Prose.parse(`
            In $$\\mathbb{Z}$$, the nilradical is $$N(\\mathbb{Z}) = \\{0\\}$$. To prove this, suppose $$a^n = 0$$ for some $$a \\in \\mathbb{Z}$$ and $$n > 0$$. Since $$\\mathbb{Z}$$ is an integral domain, $$a = 0$$. Therefore, 0 is the only nilpotent element.
        `),
        T.Prose.parse(`
            In $$\\mathbb{Z}/8\\mathbb{Z}$$, the nilradical is $$N(\\mathbb{Z}/8\\mathbb{Z}) = \\{[0]_8, [4]_8\\}$$. We can verify this: $$[4]_8^2 = [0]_8$$, and no other non-zero elements become zero when raised to any power. This is because 4 is the only element whose square is 0 in $$\\mathbb{Z}/8\\mathbb{Z}$$.
        `),
        T.Prose.parse(`
            In $$\\mathbb{Z}[x]/(x^3)$$, the nilradical is $$N(\\mathbb{Z}[x]/(x^3)) = \\langle [x] \\rangle$$. Any polynomial of the form $$[ax + bx^2]$$ is nilpotent since $$[ax + bx^2]^3 = [0]$$. These are precisely the elements in the ideal generated by $$[x]$$.
        `),
        T.Prose.parse(`
            In $$\\mathbb{Z}[x,y]/(xy)$$, the nilradical is $$N(\\mathbb{Z}[x,y]/(xy)) = \\{0\\}$$. Despite $$xy = 0$$ in this ring, no single element is nilpotent. Any non-zero polynomial in $$x$$ alone or $$y$$ alone remains non-zero when raised to any power.
        `),
        T.Prose.parse(`
            In the product ring $$\\mathbb{Z}/4\\mathbb{Z} \\times \\mathbb{Z}/9\\mathbb{Z}$$, the nilradical is $$N(\\mathbb{Z}/4\\mathbb{Z} \\times \\mathbb{Z}/9\\mathbb{Z}) = \\{([2]_4,[3]_9), ([2]_4,[6]_9), ([2]_4,[0]_9), ([0]_4,[3]_9), ([0]_4,[6]_9), ([0]_4,[0]_9)\\}$$. This is because $$[2]_4$$ is nilpotent in $$\\mathbb{Z}/4\\mathbb{Z}$$ and $$[3]_9$$ is nilpotent in $$\\mathbb{Z}/9\\mathbb{Z}$$.
        `),
    ]),
    new T.List([
        T.Prose.parse(`
            Key properties of the nilradical:
        `),
        T.Prose.parse(`
            1. The nilradical is the set of all nilpotent elements
        `),
        T.Prose.parse(`
            2. The nilradical is always an ideal
        `),
        T.Prose.parse(`
            3. A ring is reduced if and only if its nilradical is $$\\{0\\}$$
        `),
        T.Prose.parse(`
            4. The nilradical equals the intersection of all prime ideals
        `),
        T.Prose.parse(`
            5. In $$\\mathbb{Z}/n\\mathbb{Z}$$, the nilradical consists of elements whose prime factors all appear at least twice in n
        `),
    ]),
],
    T.Prose.parse(`Examples of Nilradicals in Various Rings`)
);