import * as T from "$lib/book";

export const chapter = T.BookChapter.from_exposition([
    T.List.numbered([
        T.Prose.parse(`
            Elements of the left ideal $$\\langle 1-j \\rangle$$ are of the form $$q(1-j)$$, where $$q \\in \\mathbb{H}$$.
        `),
        T.Prose.parse(`
            Consider the larger left ideal $$I$$ generated by both $$(1-j)$$ and $$i(1-j)$$. Elements of $$I$$ are of the form $$q_1(1-j) + q_2(i(1-j))$$ where $$q_1, q_2 \\in \\mathbb{H}$$.
        `),
        T.Prose.parse(`
            Clearly $$\\langle 1-j \\rangle \\subseteq I$$ since every element of $$\\langle 1-j \\rangle$$ is just a special case of an element in $$I$$ (where $$q_2 = 0$$).
        `),
        T.Prose.parse(`
            To show this containment is proper, note that $$i(1-j)$$ is in $$I$$ but not in $$\\langle 1-j \\rangle$$. If $$i(1-j)$$ were in $$\\langle 1-j \\rangle$$, there would exist some $$q = a+bi+cj+dk$$ such that $$q(1-j) = i(1-j)$$. Expanding:
            $$(a+bi+cj+dk)(1-j) = (a+c) + (b-d)i + (c+a)j + (d+b)k$$
            This cannot equal $$i-ij$$ for any values of $$a,b,c,d$$.
        `),
        T.Prose.parse(`
            Finally, $$I$$ is proper because it's not all of $$\\mathbb{H}$$ (for example, $$1$$ is not in $$I$$, as elements of $$I$$ always involve terms with $$j$$).
        `),
        T.Prose.parse(`
            Therefore, $$\\langle 1-j \\rangle$$ is not maximal as it is properly contained in another proper left ideal.
        `),
    ]),
], 
    T.Prose.parse(`Non-Example: $$\\langle 1-j \\rangle$$`)
);

// 1 - j contained in 1 - j, i(1-j)