import * as T from "$book";

export const chapter = T.Exposition.from([
    T.List.numbered([
        T.Prose.parse(`
            Let's examine the basic properties of alternating groups:
        `),
        T.Prose.parse(`
            Definition and Order:
            - Aₙ is the group of even permutations of n elements
            - |Aₙ| = n!/2 (half of the symmetric group Sₙ)
            - Aₙ is a normal subgroup of Sₙ with index 2
            - Aₙ is generated by 3-cycles
        `),
        T.Prose.parse(`
            Small Alternating Groups:
            - A₁ and A₂ are trivial groups
            - A₃ ≅ Z₃ (cyclic of order 3)
            - A₄ is the smallest non-abelian alternating group
            - A₅ is the smallest non-solvable group
        `),
        T.Prose.parse(`
            Conjugacy Classes:
            - In Aₙ, conjugacy classes of Sₙ may split
            - For example, in A₄:
              * The 3-cycles split into two classes: {(1 2 3), (1 3 2)} and {(1 2 4), (1 4 2)}
              * The double transpositions form one class: {(1 2)(3 4), (1 3)(2 4), (1 4)(2 3)}
        `),
        T.Prose.parse(`
            Key Properties:
            1. Aₙ is simple for n ≥ 5
            2. Aₙ is perfect (equal to its commutator subgroup)
            3. Aₙ has trivial center for n ≥ 4
            4. Aₙ is generated by its elements of order 3
            5. Aₙ has no proper normal subgroups for n ≥ 5
        `),
    ]),
], 
    T.Prose.parse(`Basic Properties of Alternating Groups`)
); 