import * as T from "$lib/book";

export const chapter = T.BookChapter.from_exposition([
    T.List.numbered([
        T.Prose.parse(`
            Consider the trivial group $$\\{e\\}$$, where $$e$$ is the identity element.
        `),
        T.Prose.parse(`
            The group operation table is:
            $$
            \\begin{array}{c|c}
            \\cdot & e \\\\
            \\hline
            e & e
            \\end{array}
            $$
        `),
        T.Prose.parse(`
            This group is cyclic because:
            1. It is generated by the identity element $$e$$
            2. $$e^0 = e$$ is the only element
            3. The group is isomorphic to $$\\mathbb{Z}_1$$ under addition
        `),
        T.Prose.parse(`
            This is the smallest possible cyclic group and serves as the identity element in the category of groups.
        `),
    ]),
], 
    T.Prose.parse(`Example: Trivial Group (Order 1)`)
); 