import * as T from "$lib/book";

export const chapter = T.BookChapter.from_exposition([
    T.List.numbered([
        T.Prose.parse(`
            Consider any group of order 2, which must be of the form $$\\{e, a\\}$$ where $$e$$ is the identity and $$a$$ is the non-identity element.
        `),
        T.Prose.parse(`
            The group operation table must be:
            $$
            \\begin{array}{c|cc}
            \\cdot & e & a \\\\
            \\hline
            e & e & a \\\\
            a & a & e
            \\end{array}
            $$
            This is because $$a \\cdot a$$ must equal $$e$$ (since $$a$$ must have an inverse).
        `),
        T.Prose.parse(`
            This group is cyclic because:
            1. It is generated by the non-identity element $$a$$
            2. $$a^0 = e$$ and $$a^1 = a$$ are all elements
            3. The group is isomorphic to $$\\mathbb{Z}_2$$ under addition
        `),
        T.Prose.parse(`
            Up to isomorphism, there is only one group of order 2, and it is cyclic. This is the smallest non-trivial cyclic group.
        `),
    ]),
], 
    T.Prose.parse(`Example: Groups of Order 2`)
); 