import * as T from "$lib/tex";

const prime_ideal = T.Inline.parse(
    `A "prime ideal" must be a non-trivial ideal that if ab in the ideal, then a or b must be in the ideal. This is clear because at some point, you must reach an irreducible factor. If ab is composite, and so are a and b, then either a or b is in the ideal. But, this means the factors of a or b must also be in the ideal, and so on. Eventually, this chain stops when the factors are 1 and an irreducible factor. `,
);

const purpose = T.Inline.parse(
    `The purpose of prime ideals is to be able to acheive a sense of unique factorization in dedekind domains.`
)

// An ideal I is prime if and only if its set-theoretic complement is multiplicatively closed
// The preimage of a prime ideal under a ring homomorphism is a prime ideal.
// (2) --- good
// (6) --- bad
// (2, x^5 + 5) --- bad --- (x-1)(x+1) = x^2 + 5 - 2 * 3
// Not every ideal which cannot be factored into two ideals is a prime ideal
// A nonzero principal ideal is prime if and only if it is generated by a prime element.
// Spectrum of a ring?
// krull dimensions
// height
