import * as T from "$lib/tex";

const principal_ideals = new T.Inline([
    `A "principal ideal" are all nontrivial ideals that are strictly multiples of a single mathematical object. In other words, ideals that are generated by a single element.`,
]);

const principal_ideals_motivation = new T.Inline([
    `The principal ideals are the defining characteristic of of the ideals within the ring of integers, the most familliar ring. Additionally, principal ideals imply that the fundamental theorem of arithmetic holds. In other words, principal ideals let us know that we are working in a ring that is heavily similar to the ring of integers.`
]);

const integers_proof = new T.Inline([
    `Every ideal in the ring of integers is principal. Lets imagine otherwise. Lets imagine an ideal generated by two elements, `, new T.Tex(`\\langle a, b \\rangle = \\{ a x + b y : x, y \\in \\mathbb{Z} \\}`), ` which is not principal. By Bezout's identity, for some `, new T.Tex(`x, y \\in \\mathbb{Z}`), ` we have `, new T.Tex(`d = \\gcd(a, b) = a x + b y`), `. This means that `, new T.Tex(`\\langle a, b \\rangle`), ` contains `, new T.Tex(`d`), `, and every multiple of d `, new T.Tex(`\\langle a, b \\rangle = \\{ d z : z \\in \\mathbb{Z} \\}`), `. In other words, `, new T.Tex(`\\langle d \\rangle \\subseteq \\langle a, b \\rangle`), `. However, since `, new T.Tex(`d`), ` divides both `, new T.Tex(`a`), ` and `, new T.Tex(`b`), `, that must mean `, new T.Tex(`a`), ` and`, new T.Tex(`b`), `, as well as all their multiples, are in `, new T.Tex(`\\langle d \\rangle`), `. In other words, `, new T.Tex(`\\langle a, b \\rangle \\subseteq \\langle d \\rangle`), `. But this means that `, new T.Tex(`\\langle a, b \\rangle = \\langle d \\rangle`), `, and the ideal is principal.`,
]);

const principal_etymology = new T.Inline([
    `The term "principal" meaning "chief" or "first" comes from the idea that our first exposure to ideals were via the integers, and all such ideals are of this form.`
]);



// add support for double dollar sign parsing

// every ideal in Z is principal
// zero and unit ideal are always principal
// lots of implicaitons on domains

// principal from chief, first, primary
// if every ideal is principal, then the ring is a PID and also a UFD
// do we just care about PID because it is an indication that something is a UFD?
// 