import * as T from "$book";

export const krull_dimension = T.BookChapter.from_exposition([
    T.Prose.parse(`
        The Krull dimension of a ring $$R$$ is the supremum of the lengths of all chains of prime ideals in $$R$$. Let's calculate this for several rings.
    `),
    T.List.numbered([
        T.Prose.parse(`
            In $$\\mathbb{Z}$$, the Krull dimension is 1. To prove this:
            
            1. First, we show there exists a chain of length 1: $$\\{0\\} \\subset \\langle p \\rangle$$ where $$p$$ is any prime number. This chain cannot be refined because:
                - $$\\{0\\}$$ is prime as $$\\mathbb{Z}$$ is an integral domain
                - $$\\langle p \\rangle$$ is maximal (quotient is a field)
                - No prime ideals exist between them (any ideal between them would have to be $$\\langle p^n \\rangle$$, which isn't prime for $$n > 1$$)
            
            2. No longer chains can exist because any prime ideal in $$\\mathbb{Z}$$ is either $$\\{0\\}$$ or $$\\langle p \\rangle$$ for some prime $$p$$.
        `),
        T.Prose.parse(`
            In $$k[x,y]$$ where $$k$$ is a field, the Krull dimension is 2. To prove this:
            
            1. We can construct a chain of length 2: $$\\{0\\} \\subset \\langle x \\rangle \\subset \\langle x,y \\rangle$$
            
            2. This chain is maximal because:
                - $$\\{0\\}$$ is prime as $$k[x,y]$$ is an integral domain
                - $$\\langle x \\rangle$$ is prime (quotient $$k[x,y]/\\langle x \\rangle \\cong k[y]$$ is an integral domain)
                - $$\\langle x,y \\rangle$$ is maximal (quotient is field $$k$$)
                - No prime ideals can exist between these by degree considerations
            
            3. No longer chains can exist by Krull's Height Theorem, as $$k[x,y]$$ is generated by 2 elements.
        `),
        T.Prose.parse(`
            In $$\\mathbb{Z}/8\\mathbb{Z}$$, the Krull dimension is 0. To prove this:
            
            1. First, let's identify all prime ideals:
                - A prime ideal $$P$$ must contain all nilpotent elements
                - In $$\\mathbb{Z}/8\\mathbb{Z}$$, $$[2]_8^3 = [0]_8$$, so $$[2]_8$$ is nilpotent
                - Therefore $$\\langle [2]_8 \\rangle$$ must be contained in any prime ideal
                - But $$\\langle [2]_8 \\rangle$$ is maximal (quotient is $$\\mathbb{Z}/2\\mathbb{Z}$$)
                - Thus $$\\langle [2]_8 \\rangle$$ is the only prime ideal
            
            2. With only one prime ideal, no proper chains can exist
            3. Therefore, the Krull dimension is 0
        `),
    ]),
    T.List.numbered([
        T.Prose.parse(`
            Key observations about Krull dimension:
        `),
        T.Prose.parse(`
            1. For a PID, the Krull dimension is always 1
        `),
        T.Prose.parse(`
            2. For polynomial rings, $$\\dim k[x_1,...,x_n] = n$$ over a field
        `),
        T.Prose.parse(`
            3. Artinian rings have Krull dimension 0
        `),
        T.Prose.parse(`
            4. The Krull dimension is preserved under localization
        `),
    ]),
],
    T.Prose.parse(`Examples of Calculating Krull Dimension`)
);