import * as T from "$lib/book";

export const chapter = T.BookChapter.from_exposition([
    T.List.numbered([
        T.Prose.parse(`
            The simplicity of alternating groups for n ≥ 5 is a fundamental result in group theory.
            Let's examine why Aₙ is simple for n ≥ 5:
        `),
        T.Prose.parse(`
            Case 1: A₅ is Simple
            We can prove A₅ is simple by examining its normal subgroups:
            
            - Order of A₅ is 60
            - Possible orders of normal subgroups must divide 60
            - The only possible orders are 1, 2, 3, 4, 5, 6, 10, 12, 15, 20, 30, 60
            - But A₅ has no subgroup of order 30 (would have index 2)
            - The only normal subgroups are {e} and A₅ itself
        `),
        T.Prose.parse(`
            Case 2: A₄ is Not Simple
            A₄ has a non-trivial normal subgroup:
            
            - The Klein four-group V = {e, (1 2)(3 4), (1 3)(2 4), (1 4)(2 3)}
            - V is normal in A₄
            - The quotient group A₄/V ≅ Z₃
            - This shows A₄ is solvable but not simple
        `),
        T.Prose.parse(`
            General Proof for n ≥ 5:
            The proof that Aₙ is simple for n ≥ 5 relies on:
            
            1. Showing that any non-trivial normal subgroup N contains a 3-cycle
            2. Proving that N must contain all 3-cycles
            3. Since Aₙ is generated by 3-cycles, N = Aₙ
            4. The only normal subgroups are {e} and Aₙ itself
        `),
        T.Prose.parse(`
            Key observations about simplicity:
            1. Aₙ is simple for n ≥ 5
            2. A₄ is the largest non-simple alternating group
            3. The simplicity of A₅ is crucial in Galois theory
            4. This result is fundamental to the classification of finite simple groups
            5. The proof uses the rich structure of permutation groups
        `),
    ]),
], 
    T.Prose.parse(`Simplicity of Alternating Groups`)
); 